# First exploration of data

## Explanations about the values

There are 25 variables:

- ID: ID of each client
- LIMIT_BAL: Amount of given credit in NT dollars (includes individual and family/supplementary credit
- SEX: Gender (1=male, 2=female)
- EDUCATION: (1=graduate school, 2=university, 3=high school, 4=others, 5=unknown, 6=unknown)
- MARRIAGE: Marital status (1=married, 2=single, 3=others)
- AGE: Age in years
- PAY_0: Repayment status in September, 2005 (-1=pay duly, 1=payment delay for one month, 2=payment delay for two months, … 8=payment delay for eight months, 9=payment delay for nine months and above)
- PAY_2: Repayment status in August, 2005 (scale same as above)
- PAY_3: Repayment status in July, 2005 (scale same as above)
- PAY_4: Repayment status in June, 2005 (scale same as above)
- PAY_5: Repayment status in May, 2005 (scale same as above)
- PAY_6: Repayment status in April, 2005 (scale same as above)
- BILL_AMT1: Amount of bill statement in September, 2005 (NT dollar)
- BILL_AMT2: Amount of bill statement in August, 2005 (NT dollar)
- BILL_AMT3: Amount of bill statement in July, 2005 (NT dollar)
- BILL_AMT4: Amount of bill statement in June, 2005 (NT dollar)
- BILL_AMT5: Amount of bill statement in May, 2005 (NT dollar)
- BILL_AMT6: Amount of bill statement in April, 2005 (NT dollar)
- PAY_AMT1: Amount of previous payment in September, 2005 (NT dollar)
- PAY_AMT2: Amount of previous payment in August, 2005 (NT dollar)
- PAY_AMT3: Amount of previous payment in July, 2005 (NT dollar)
- PAY_AMT4: Amount of previous payment in June, 2005 (NT dollar)
- PAY_AMT5: Amount of previous payment in May, 2005 (NT dollar)
- PAY_AMT6: Amount of previous payment in April, 2005 (NT dollar)
- default.payment.next.month: Default payment (1=yes, 0=no)

In [70]:
import numpy as np
import pandas as pd

In [71]:
pd.options.display.max_columns = None

In [72]:
df = pd.read_csv("../data/UCI_Credit_Card.csv")
df

ID  LIMIT_BAL  SEX  EDUCATION  MARRIAGE  AGE  PAY_0  PAY_2  PAY_3  \
0          1    20000.0    2          2         1   24      2      2     -1   
1          2   120000.0    2          2         2   26     -1      2      0   
2          3    90000.0    2          2         2   34      0      0      0   
3          4    50000.0    2          2         1   37      0      0      0   
4          5    50000.0    1          2         1   57     -1      0     -1   
...      ...        ...  ...        ...       ...  ...    ...    ...    ...   
29995  29996   220000.0    1          3         1   39      0      0      0   
29996  29997   150000.0    1          3         2   43     -1     -1     -1   
29997  29998    30000.0    1          2         2   37      4      3      2   
29998  29999    80000.0    1          3         1   41      1     -1      0   
29999  30000    50000.0    1          2         1   46      0      0      0   

       PAY_4  PAY_5  PAY_6  BILL_AMT1  BILL_AMT2  BILL_AMT3  BILL_AMT4  \
0         -1     -2     -2     3913.0     3102.0      689.0        0.0   
1          0      0      2     2682.0     1725.0     2682.0     3272.0   
2          0      0      0    29239.0    14027.0    13559.0    14331.0   
3          0      0      0    46990.0    48233.0    49291.0    28314.0   
4          0      0      0     8617.0     5670.0    35835.0    20940.0   
...      ...    ...    ...        ...        ...        ...        ...   
29995      0      0      0   188948.0   192815.0   208365.0    88004.0   
29996     -1      0      0     1683.0     1828.0     3502.0     8979.0   
29997     -1      0      0     3565.0     3356.0     2758.0    20878.0   
29998      0      0     -1    -1645.0    78379.0    76304.0    52774.0   
29999      0      0      0    47929.0    48905.0    49764.0    36535.0   

       BILL_AMT5  BILL_AMT6  PAY_AMT1  PAY_AMT2  PAY_AMT3  PAY_AMT4  PAY_AMT5  \
0            0.0        0.0       0.0     689.0       0.0       0.0       0.0   
1         3455.0     3261.0       0.0    1000.0    1000.0    1000.0       0.0   
2        14948.0    15549.0    1518.0    1500.0    1000.0    1000.0    1000.0   
3        28959.0    29547.0    2000.0    2019.0    1200.0    1100.0    1069.0   
4        19146.0    19131.0    2000.0   36681.0   10000.0    9000.0     689.0   
...          ...        ...       ...       ...       ...       ...       ...   
29995    31237.0    15980.0    8500.0   20000.0    5003.0    3047.0    5000.0   
29996     5190.0        0.0    1837.0    3526.0    8998.0     129.0       0.0   
29997    20582.0    19357.0       0.0       0.0   22000.0    4200.0    2000.0   
29998    11855.0    48944.0   85900.0    3409.0    1178.0    1926.0   52964.0   
29999    32428.0    15313.0    2078.0    1800.0    1430.0    1000.0    1000.0   

       PAY_AMT6  default.payment.next.month  
0           0.0                           1  
1        2000.0                           1  
2        5000.0                           0  
3        1000.0                           0  
4         679.0                           0  
...         ...                         ...  
29995    1000.0                           0  
29996       0.0                           0  
29997    3100.0                           1  
29998    1804.0                           1  
29999    1000.0                           1  

[30000 rows x 25 columns]

In [73]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 25 columns):
 #   Column                      Non-Null Count  Dtype  
---  ------                      --------------  -----  
 0   ID                          30000 non-null  int64  
 1   LIMIT_BAL                   30000 non-null  float64
 2   SEX                         30000 non-null  int64  
 3   EDUCATION                   30000 non-null  int64  
 4   MARRIAGE                    30000 non-null  int64  
 5   AGE                         30000 non-null  int64  
 6   PAY_0                       30000 non-null  int64  
 7   PAY_2                       30000 non-null  int64  
 8   PAY_3                       30000 non-null  int64  
 9   PAY_4                       30000 non-null  int64  
 10  PAY_5                       30000 non-null  int64  
 11  PAY_6                       30000 non-null  int64  
 12  BILL_AMT1                   30000 non-null  float64
 13  BILL_AMT2                   300

In [74]:
df.describe()

ID       LIMIT_BAL           SEX     EDUCATION      MARRIAGE  \
count  30000.000000    30000.000000  30000.000000  30000.000000  30000.000000   
mean   15000.500000   167484.322667      1.603733      1.853133      1.551867   
std     8660.398374   129747.661567      0.489129      0.790349      0.521970   
min        1.000000    10000.000000      1.000000      0.000000      0.000000   
25%     7500.750000    50000.000000      1.000000      1.000000      1.000000   
50%    15000.500000   140000.000000      2.000000      2.000000      2.000000   
75%    22500.250000   240000.000000      2.000000      2.000000      2.000000   
max    30000.000000  1000000.000000      2.000000      6.000000      3.000000   

                AGE         PAY_0         PAY_2         PAY_3         PAY_4  \
count  30000.000000  30000.000000  30000.000000  30000.000000  30000.000000   
mean      35.485500     -0.016700     -0.133767     -0.166200     -0.220667   
std        9.217904      1.123802      1.197186      1.196868      1.169139   
min       21.000000     -2.000000     -2.000000     -2.000000     -2.000000   
25%       28.000000     -1.000000     -1.000000     -1.000000     -1.000000   
50%       34.000000      0.000000      0.000000      0.000000      0.000000   
75%       41.000000      0.000000      0.000000      0.000000      0.000000   
max       79.000000      8.000000      8.000000      8.000000      8.000000   

              PAY_5         PAY_6      BILL_AMT1      BILL_AMT2     BILL_AMT3  \
count  30000.000000  30000.000000   30000.000000   30000.000000  3.000000e+04   
mean      -0.266200     -0.291100   51223.330900   49179.075167  4.701315e+04   
std        1.133187      1.149988   73635.860576   71173.768783  6.934939e+04   
min       -2.000000     -2.000000 -165580.000000  -69777.000000 -1.572640e+05   
25%       -1.000000     -1.000000    3558.750000    2984.750000  2.666250e+03   
50%        0.000000      0.000000   22381.500000   21200.000000  2.008850e+04   
75%        0.000000      0.000000   67091.000000   64006.250000  6.016475e+04   
max        8.000000      8.000000  964511.000000  983931.000000  1.664089e+06   

           BILL_AMT4      BILL_AMT5      BILL_AMT6       PAY_AMT1  \
count   30000.000000   30000.000000   30000.000000   30000.000000   
mean    43262.948967   40311.400967   38871.760400    5663.580500   
std     64332.856134   60797.155770   59554.107537   16563.280354   
min   -170000.000000  -81334.000000 -339603.000000       0.000000   
25%      2326.750000    1763.000000    1256.000000    1000.000000   
50%     19052.000000   18104.500000   17071.000000    2100.000000   
75%     54506.000000   50190.500000   49198.250000    5006.000000   
max    891586.000000  927171.000000  961664.000000  873552.000000   

           PAY_AMT2      PAY_AMT3       PAY_AMT4       PAY_AMT5  \
count  3.000000e+04   30000.00000   30000.000000   30000.000000   
mean   5.921163e+03    5225.68150    4826.076867    4799.387633   
std    2.304087e+04   17606.96147   15666.159744   15278.305679   
min    0.000000e+00       0.00000       0.000000       0.000000   
25%    8.330000e+02     390.00000     296.000000     252.500000   
50%    2.009000e+03    1800.00000    1500.000000    1500.000000   
75%    5.000000e+03    4505.00000    4013.250000    4031.500000   
max    1.684259e+06  896040.00000  621000.000000  426529.000000   

            PAY_AMT6  default.payment.next.month  
count   30000.000000                30000.000000  
mean     5215.502567                    0.221200  
std     17777.465775                    0.415062  
min         0.000000                    0.000000  
25%       117.750000                    0.000000  
50%      1500.000000                    0.000000  
75%      4000.000000                    0.000000  
max    528666.000000                    1.000000

## Make some changes

In [75]:
# Make ID the index
df = df.set_index("ID")
df

LIMIT_BAL  SEX  EDUCATION  MARRIAGE  AGE  PAY_0  PAY_2  PAY_3  PAY_4  \
ID                                                                            
1        20000.0    2          2         1   24      2      2     -1     -1   
2       120000.0    2          2         2   26     -1      2      0      0   
3        90000.0    2          2         2   34      0      0      0      0   
4        50000.0    2          2         1   37      0      0      0      0   
5        50000.0    1          2         1   57     -1      0     -1      0   
...          ...  ...        ...       ...  ...    ...    ...    ...    ...   
29996   220000.0    1          3         1   39      0      0      0      0   
29997   150000.0    1          3         2   43     -1     -1     -1     -1   
29998    30000.0    1          2         2   37      4      3      2     -1   
29999    80000.0    1          3         1   41      1     -1      0      0   
30000    50000.0    1          2         1   46      0      0      0      0   

       PAY_5  PAY_6  BILL_AMT1  BILL_AMT2  BILL_AMT3  BILL_AMT4  BILL_AMT5  \
ID                                                                           
1         -2     -2     3913.0     3102.0      689.0        0.0        0.0   
2          0      2     2682.0     1725.0     2682.0     3272.0     3455.0   
3          0      0    29239.0    14027.0    13559.0    14331.0    14948.0   
4          0      0    46990.0    48233.0    49291.0    28314.0    28959.0   
5          0      0     8617.0     5670.0    35835.0    20940.0    19146.0   
...      ...    ...        ...        ...        ...        ...        ...   
29996      0      0   188948.0   192815.0   208365.0    88004.0    31237.0   
29997      0      0     1683.0     1828.0     3502.0     8979.0     5190.0   
29998      0      0     3565.0     3356.0     2758.0    20878.0    20582.0   
29999      0     -1    -1645.0    78379.0    76304.0    52774.0    11855.0   
30000      0      0    47929.0    48905.0    49764.0    36535.0    32428.0   

       BILL_AMT6  PAY_AMT1  PAY_AMT2  PAY_AMT3  PAY_AMT4  PAY_AMT5  PAY_AMT6  \
ID                                                                             
1            0.0       0.0     689.0       0.0       0.0       0.0       0.0   
2         3261.0       0.0    1000.0    1000.0    1000.0       0.0    2000.0   
3        15549.0    1518.0    1500.0    1000.0    1000.0    1000.0    5000.0   
4        29547.0    2000.0    2019.0    1200.0    1100.0    1069.0    1000.0   
5        19131.0    2000.0   36681.0   10000.0    9000.0     689.0     679.0   
...          ...       ...       ...       ...       ...       ...       ...   
29996    15980.0    8500.0   20000.0    5003.0    3047.0    5000.0    1000.0   
29997        0.0    1837.0    3526.0    8998.0     129.0       0.0       0.0   
29998    19357.0       0.0       0.0   22000.0    4200.0    2000.0    3100.0   
29999    48944.0   85900.0    3409.0    1178.0    1926.0   52964.0    1804.0   
30000    15313.0    2078.0    1800.0    1430.0    1000.0    1000.0    1000.0   

       default.payment.next.month  
ID                                 
1                               1  
2                               1  
3                               0  
4                               0  
5                               0  
...                           ...  
29996                           0  
29997                           0  
29998                           1  
29999                           1  
30000                           1  

[30000 rows x 24 columns]

In [76]:
print(df["PAY_0"].unique())
print(df["PAY_2"].unique())
print(df["PAY_3"].unique())
print(df["PAY_4"].unique())
print(df["PAY_5"].unique())
print(df["PAY_6"].unique())

[ 2 -1  0 -2  1  3  4  8  7  5  6]
[ 2  0 -1 -2  3  5  7  4  1  6  8]
[-1  0  2 -2  3  4  6  7  1  5  8]
[-1  0 -2  2  3  4  5  7  6  1  8]
[-2  0 -1  2  3  5  4  7  8  6]
[-2  2  0 -1  3  6  4  7  8  5]


In [77]:
# Change a columns name.
df["PAY_1"] = df["PAY_0"]
df = df.drop(["PAY_0"], axis=1)
df

LIMIT_BAL  SEX  EDUCATION  MARRIAGE  AGE  PAY_2  PAY_3  PAY_4  PAY_5  \
ID                                                                            
1        20000.0    2          2         1   24      2     -1     -1     -2   
2       120000.0    2          2         2   26      2      0      0      0   
3        90000.0    2          2         2   34      0      0      0      0   
4        50000.0    2          2         1   37      0      0      0      0   
5        50000.0    1          2         1   57      0     -1      0      0   
...          ...  ...        ...       ...  ...    ...    ...    ...    ...   
29996   220000.0    1          3         1   39      0      0      0      0   
29997   150000.0    1          3         2   43     -1     -1     -1      0   
29998    30000.0    1          2         2   37      3      2     -1      0   
29999    80000.0    1          3         1   41     -1      0      0      0   
30000    50000.0    1          2         1   46      0      0      0      0   

       PAY_6  BILL_AMT1  BILL_AMT2  BILL_AMT3  BILL_AMT4  BILL_AMT5  \
ID                                                                    
1         -2     3913.0     3102.0      689.0        0.0        0.0   
2          2     2682.0     1725.0     2682.0     3272.0     3455.0   
3          0    29239.0    14027.0    13559.0    14331.0    14948.0   
4          0    46990.0    48233.0    49291.0    28314.0    28959.0   
5          0     8617.0     5670.0    35835.0    20940.0    19146.0   
...      ...        ...        ...        ...        ...        ...   
29996      0   188948.0   192815.0   208365.0    88004.0    31237.0   
29997      0     1683.0     1828.0     3502.0     8979.0     5190.0   
29998      0     3565.0     3356.0     2758.0    20878.0    20582.0   
29999     -1    -1645.0    78379.0    76304.0    52774.0    11855.0   
30000      0    47929.0    48905.0    49764.0    36535.0    32428.0   

       BILL_AMT6  PAY_AMT1  PAY_AMT2  PAY_AMT3  PAY_AMT4  PAY_AMT5  PAY_AMT6  \
ID                                                                             
1            0.0       0.0     689.0       0.0       0.0       0.0       0.0   
2         3261.0       0.0    1000.0    1000.0    1000.0       0.0    2000.0   
3        15549.0    1518.0    1500.0    1000.0    1000.0    1000.0    5000.0   
4        29547.0    2000.0    2019.0    1200.0    1100.0    1069.0    1000.0   
5        19131.0    2000.0   36681.0   10000.0    9000.0     689.0     679.0   
...          ...       ...       ...       ...       ...       ...       ...   
29996    15980.0    8500.0   20000.0    5003.0    3047.0    5000.0    1000.0   
29997        0.0    1837.0    3526.0    8998.0     129.0       0.0       0.0   
29998    19357.0       0.0       0.0   22000.0    4200.0    2000.0    3100.0   
29999    48944.0   85900.0    3409.0    1178.0    1926.0   52964.0    1804.0   
30000    15313.0    2078.0    1800.0    1430.0    1000.0    1000.0    1000.0   

       default.payment.next.month  PAY_1  
ID                                        
1                               1      2  
2                               1     -1  
3                               0      0  
4                               0      0  
5                               0     -1  
...                           ...    ...  
29996                           0      0  
29997                           0     -1  
29998                           1      4  
29999                           1      1  
30000                           1      0  

[30000 rows x 24 columns]

In [78]:
# Change some values without significations into "Uknown" value.
df[df["EDUCATION"] == 6] = 5
df[df["EDUCATION"] == 0] = 5
df

LIMIT_BAL  SEX  EDUCATION  MARRIAGE  AGE  PAY_2  PAY_3  PAY_4  PAY_5  \
ID                                                                            
1        20000.0    2          2         1   24      2     -1     -1     -2   
2       120000.0    2          2         2   26      2      0      0      0   
3        90000.0    2          2         2   34      0      0      0      0   
4        50000.0    2          2         1   37      0      0      0      0   
5        50000.0    1          2         1   57      0     -1      0      0   
...          ...  ...        ...       ...  ...    ...    ...    ...    ...   
29996   220000.0    1          3         1   39      0      0      0      0   
29997   150000.0    1          3         2   43     -1     -1     -1      0   
29998    30000.0    1          2         2   37      3      2     -1      0   
29999    80000.0    1          3         1   41     -1      0      0      0   
30000    50000.0    1          2         1   46      0      0      0      0   

       PAY_6  BILL_AMT1  BILL_AMT2  BILL_AMT3  BILL_AMT4  BILL_AMT5  \
ID                                                                    
1         -2     3913.0     3102.0      689.0        0.0        0.0   
2          2     2682.0     1725.0     2682.0     3272.0     3455.0   
3          0    29239.0    14027.0    13559.0    14331.0    14948.0   
4          0    46990.0    48233.0    49291.0    28314.0    28959.0   
5          0     8617.0     5670.0    35835.0    20940.0    19146.0   
...      ...        ...        ...        ...        ...        ...   
29996      0   188948.0   192815.0   208365.0    88004.0    31237.0   
29997      0     1683.0     1828.0     3502.0     8979.0     5190.0   
29998      0     3565.0     3356.0     2758.0    20878.0    20582.0   
29999     -1    -1645.0    78379.0    76304.0    52774.0    11855.0   
30000      0    47929.0    48905.0    49764.0    36535.0    32428.0   

       BILL_AMT6  PAY_AMT1  PAY_AMT2  PAY_AMT3  PAY_AMT4  PAY_AMT5  PAY_AMT6  \
ID                                                                             
1            0.0       0.0     689.0       0.0       0.0       0.0       0.0   
2         3261.0       0.0    1000.0    1000.0    1000.0       0.0    2000.0   
3        15549.0    1518.0    1500.0    1000.0    1000.0    1000.0    5000.0   
4        29547.0    2000.0    2019.0    1200.0    1100.0    1069.0    1000.0   
5        19131.0    2000.0   36681.0   10000.0    9000.0     689.0     679.0   
...          ...       ...       ...       ...       ...       ...       ...   
29996    15980.0    8500.0   20000.0    5003.0    3047.0    5000.0    1000.0   
29997        0.0    1837.0    3526.0    8998.0     129.0       0.0       0.0   
29998    19357.0       0.0       0.0   22000.0    4200.0    2000.0    3100.0   
29999    48944.0   85900.0    3409.0    1178.0    1926.0   52964.0    1804.0   
30000    15313.0    2078.0    1800.0    1430.0    1000.0    1000.0    1000.0   

       default.payment.next.month  PAY_1  
ID                                        
1                               1      2  
2                               1     -1  
3                               0      0  
4                               0      0  
5                               0     -1  
...                           ...    ...  
29996                           0      0  
29997                           0     -1  
29998                           1      4  
29999                           1      1  
30000                           1      0  

[30000 rows x 24 columns]

In [79]:
# One hot encoding.
def One_hot_encoding(df:pd.DataFrame, column_name:str) -> pd.DataFrame:
    new_columns = pd.get_dummies(df[f"{column_name}"], prefix=f"{column_name}")
    df = df.drop([f"{column_name}"], axis=1)
    df = pd.concat([df, new_columns], axis=1)
    return df

In [80]:
# Create new columns using one hot encoding.
columns_names = ["SEX", "EDUCATION", "MARRIAGE", "PAY_1", "PAY_2", "PAY_3", "PAY_4", "PAY_5", "PAY_6"]

for name in columns_names:
    df = One_hot_encoding(df, name)

print(df)

       LIMIT_BAL  AGE  BILL_AMT1  BILL_AMT2  BILL_AMT3  BILL_AMT4  BILL_AMT5  \
ID                                                                             
1        20000.0   24     3913.0     3102.0      689.0        0.0        0.0   
2       120000.0   26     2682.0     1725.0     2682.0     3272.0     3455.0   
3        90000.0   34    29239.0    14027.0    13559.0    14331.0    14948.0   
4        50000.0   37    46990.0    48233.0    49291.0    28314.0    28959.0   
5        50000.0   57     8617.0     5670.0    35835.0    20940.0    19146.0   
...          ...  ...        ...        ...        ...        ...        ...   
29996   220000.0   39   188948.0   192815.0   208365.0    88004.0    31237.0   
29997   150000.0   43     1683.0     1828.0     3502.0     8979.0     5190.0   
29998    30000.0   37     3565.0     3356.0     2758.0    20878.0    20582.0   
29999    80000.0   41    -1645.0    78379.0    76304.0    52774.0    11855.0   
30000    50000.0   46    47929.0    4890

In [81]:
df.to_csv("../data/preprocessed_data.csv")